### ISSUE TITLE
Remove irrelevantly old status updates

### ISSUE THREAD

**Issue by michaelwisely** [siggame/status#4]
Many of the status update posts are too old to be relevant. Plants is over. Competitors and devs alike may see old posts and get confused.

Please remove all old posts for all categories. If that means removing all status updates for a category, that's totally fine. The Jekyll templates may need to be updated to deal with empty statuses... but maybe not. I'm not sure what they'll do.

**Comment by jonsimington** [comment]
You got it, boss. It'll be done before tomorrow. 

—
